const poems = [
  "she carries the oceans to my toes",
  "and every time I say to myself",
  "I am in love.",
  "I dont know how-",
  "but I have found the color",
  "between black and white,",
  "no wonder they have always been silent.",
  "",
  "she carries the oceans to my toes",
  "and every time I say to myself",
  "I am in love.",
  "I dont know how-",
  "but I have found the color",
  "between black and white,",
  "no wonder they have always been silent.",
  "",
  "she carries the oceans to my toes",
  "and every time I say to myself",
  "I am in love.",
  "I dont know how-",
  "but I have found the color",
  "between black and white,",
  "no wonder they have always been silent.",
  "",
  "she carries the oceans to my toes",
  "and every time I say to myself",
  "I am in love.",
  "I dont know how-",
  "but I have found the color",
  "between black and white,",
  "no wonder they have always been silent.",
  "",
  "she carries the oceans to my toes",
  "and every time I say to myself",
  "I am in love.",
  "I dont know how-",
  "but I have found the color",
  "between black and white,",
  "no wonder they have always been silent.",
  "",
];

const comments = [
  "Sanusi Muhyideen: Beautiful",
  "Exolee Olayemi: This is awesome",
  "Muhyideen Kolawole: I love your poem and it is very beautiful and colorful",
  "Sanusi Muhyideen: Beautiful",
  "Exolee Olayemi: This is awesome",
  "Muhyideen Kolawole: I love your poem",
  "Sanusi Muhyideen: Beautiful",
  "Exolee Olayemi: This is awesome",
  "Muhyideen Kolawole: I love your poem",
];

export { comments, poems };
